export type Language = "zh" | "en" | "es";
export const LANGUAGE_STORAGE_KEY = "neiku.ui-language";
export const LANGUAGES: readonly Language[] = ["zh", "en", "es"];
export function isLanguage(value: unknown): value is Language {
  return LANGUAGES.includes(value as Language);
}

// Source strings are display keys only. Never translate API values, identifiers or exports.
export const messages: Record<string, readonly [string, string]> = {
  "没有员工状态页面的访问权限": ["No access to staff status", "Sin acceso al estado del personal"],
  "请联系管理员授权。": ["Ask an administrator for access.", "Solicite acceso al administrador."],
  "返回内库": ["Back to 内库", "Volver a 内库"],
  "员工": ["Staff", "Personal"], "员工 ID": ["Employee ID", "ID empleado"],
  "未选择": ["None", "Ninguno"], "已选 {0}": ["{0} selected", "{0} elegidos"],
  "其他": ["Other", "Otro"], "未标注": ["Unmarked", "Sin tipo"],
  "爆品": ["Hot", "Popular"], "单件": ["Single", "Simple"], "多件": ["Multi", "Múltiple"], "混件": ["Mixed", "Mixto"],
  "库龄": ["Age", "Días"], "容量": ["Capacity", "Capacidad"],
  "当日不在岗": ["Off-duty today", "Ausencia hoy"], "组织": ["Organization", "Organización"],
  "仓外": ["Outside", "Exterior"], "出库": ["Outbound", "Salida"],
  "仓库主管": ["Supervisor", "Supervisor"], "系统管理员": ["Administrator", "Administrador"], "操作员": ["Operator", "Operador"],
  "协同人员": ["Helpers", "Colaboradores"], "移入": ["Inbound", "Entrada"], "移出": ["Outbound", "Salida"],
  "原位记录": ["Same location", "Misma ubicación"], "手动调整": ["Manual edit", "Ajuste manual"],
  "备货区迁移": ["Reserve move", "Traslado reserva"], "退回备货区": ["Return to reserve", "Devolver a reserva"],
  "退回备货": ["Return stock", "Devolver stock"], "待领取": ["Unclaimed", "Sin asignar"],
  "部分完成": ["Partly done", "Parcial"], "部分送达": ["Part delivered", "Entrega parcial"],
  "批量待处理": ["Batch pending", "Lote pendiente"], "待创建": ["Not created", "Sin crear"],
  "库位汇总": ["Location totals", "Totales ubicación"], "SKU汇总": ["SKU totals", "Totales SKU"],
  "备货托数": ["Reserve pallets", "Palés reserva"], "历史操作数": ["Actions", "Acciones"],
  "当前SKU": ["Current SKU", "SKU actual"], "当前库位": ["Current location", "Ubicación actual"],
  "当前托盘数": ["Current pallets", "Palés actuales"],
  "下班": ["Sign out", "Salida"], "结束时间": ["End time", "Hora final"], "已修改": ["Edited", "Modificado"],
  "日期范围内曾 Sign In": ["Signed in within date range", "Con entrada en el rango"],
  "正在处理其他工作项目": ["Working on other tasks", "En otras tareas"],
  "正在处理波次、混件扫描或单件扫描": ["Picking or scanning", "Picking o escaneo"],
  "在岗且暂无任务": ["On duty with no task", "En turno sin tarea"],
  "拣货员工": ["Pickers", "Personal de picking"], "仓务员工": ["Warehouse staff", "Personal de almacén"], "待命员工": ["Standby staff", "Personal disponible"],
  "移除未开始的波次": ["Remove unstarted wave", "Quitar ola no iniciada"],
  "已完成波次不能移除": ["Completed waves cannot be removed", "No se pueden quitar olas finalizadas"],
  "已有人员参与，不能移除": ["Participants exist; cannot remove", "Tiene participantes; no se puede quitar"],
  "没有符合条件的 SKU": ["No matching SKUs", "Sin SKU coincidentes"],
  "没有符合条件的 SKU 主数据": ["No matching catalog entries", "Sin entradas coincidentes en el catálogo"],
  "没有符合条件的备货库位或托盘": ["No matching reserve locations or pallets", "Sin ubicaciones ni palés coincidentes"],
  "没有符合条件的库位": ["No matching locations", "Sin ubicaciones coincidentes"],
  "请选择 SKU 查看流转明细": ["Select a SKU to view movements", "Elija un SKU para ver sus movimientos"],
  "请选择库位查看历史明细": ["Select a location to view history", "Elija una ubicación para ver el historial"],
  "当前没有待办任务": ["No pending tasks", "Sin tareas pendientes"], "暂无任务明细": ["No task details", "Sin detalles de tarea"],
  "当前条件下没有历史记录": ["No matching history", "Sin historial coincidente"],
  "搜索 SKU、托盘号、备注、库位、任务号或操作人": ["Search SKU, pallet, note, location, task or operator", "Buscar SKU, palé, nota, ubicación, tarea u operador"],
  "搜索 SKU、托盘号或备注": ["Search SKU, pallet or note", "Buscar SKU, palé o nota"],
  "搜索库位、SKU 或托盘号": ["Search location, SKU or pallet", "Buscar ubicación, SKU o palé"],
  "请填写 SKU": ["Enter a SKU", "Ingrese un SKU"], "请至少输入一名员工": ["Enter at least one employee", "Ingrese al menos un empleado"],
  "请扫描有效员工卡": ["Scan a valid employee card", "Escanee una tarjeta válida"],
  "员工状态已变化，请重新选择操作后确认。": ["Employee status changed. Choose the action again before confirming.", "Cambió el estado del empleado. Elija de nuevo la acción antes de confirmar."],
  "所选任务已不可用，请重新选择。": ["This task is no longer available. Choose another.", "La tarea ya no está disponible. Elija otra."],
  "当前没有可完结的负责人波次": ["No lead wave available to finish", "No hay ola como titular para finalizar"],
  "请先选择至少一个可操作托盘": ["Select at least one available pallet", "Seleccione al menos un palé disponible"],
  "未识别到有效波次，请检查波次号。": ["No valid waves found. Check wave numbers.", "No se encontraron olas válidas. Revise sus números."],
  "扫描内容不是有效的员工工卡，请对准员工 ID 条码或二维码": ["Not a valid employee card. Scan the employee barcode or QR code.", "Tarjeta no válida. Escanee el código de barras o QR del empleado."],
  "未识别到员工工卡，请重新扫描": ["Employee card not detected. Scan again.", "No se detectó tarjeta. Escanee de nuevo."],
  "摄像头启动失败，请检查浏览器权限后重试": ["Camera failed to start. Check browser permissions.", "No se pudo iniciar la cámara. Revise los permisos del navegador."],
  "摄像头扫描需要使用 HTTPS，并允许浏览器访问摄像头": ["Camera scanning needs HTTPS and camera permission.", "El escaneo requiere HTTPS y permiso para usar la cámara."],
  "摄像头权限未开启，请在浏览器设置中允许本网站使用摄像头": ["Allow this site to use the camera in browser settings.", "Permita a este sitio usar la cámara en la configuración del navegador."],
  "摄像头正被其他应用占用，请关闭其他应用后重试": ["Another app is using the camera. Close it and retry.", "Otra aplicación usa la cámara. Ciérrela y reintente."],
  "摄像头画面尚未准备好": ["Camera is not ready yet", "La cámara aún no está lista"],
  "没有找到可用的摄像头": ["No available camera found", "No se encontró cámara disponible"],
  "员工记录尚未载入": ["Employee record is not loaded", "El registro del empleado no está cargado"],
  "时间已修改": ["Time updated", "Hora actualizada"], "时间修改失败": ["Could not update time", "No se pudo actualizar la hora"],
  "保存失败": ["Save failed", "Error al guardar"], "创建失败": ["Creation failed", "Error al crear"],
  "删除失败": ["Delete failed", "Error al borrar"], "入库失败": ["Put-away failed", "Error de entrada"],
  "扫描操作失败": ["Scan action failed", "Error en la acción de escaneo"],
  "工作记录读取失败": ["Could not load work records", "No se pudieron cargar los registros laborales"],
  "任务数据读取失败": ["Could not load tasks", "No se pudieron cargar las tareas"],
  "员工信息读取失败": ["Could not load employee", "No se pudo cargar el empleado"],
  "员工数据读取失败": ["Could not load staff", "No se pudo cargar el personal"],
  "员工数据更新失败": ["Could not update employee", "No se pudo actualizar el empleado"],
  "员工状态更新失败": ["Could not update staff status", "No se pudo actualizar el estado"],
  "新增员工失败": ["Could not add employee", "No se pudo añadir el empleado"],
  "看板数据读取失败": ["Could not load the board", "No se pudo cargar el panel"],
  "波次操作失败": ["Wave action failed", "Error al operar la ola"], "波次导入失败": ["Wave import failed", "Error al importar olas"],
  "员工扫描素材导出失败": ["Badge export failed", "Error al exportar tarjetas"],
  "考勤导出失败": ["Attendance export failed", "Error al exportar asistencia"],
  "工作汇总导出失败": ["Summary export failed", "Error al exportar resumen"],
  "现场看板导出失败": ["Board export failed", "Error al exportar panel"],
  "权限保存失败": ["Could not save permissions", "No se pudieron guardar los permisos"],
  "内部账号已创建": ["Account created", "Cuenta creada"], "账号已停用": ["Account disabled", "Cuenta desactivada"],
  "账号已启用": ["Account enabled", "Cuenta activada"], "账号已删除": ["Account deleted", "Cuenta eliminada"],
  "账号权限已更新": ["Permissions updated", "Permisos actualizados"],
  "已同步其他设备的最新操作": ["Latest changes synced", "Cambios recientes sincronizados"],
  "托盘记录已更新": ["Pallet updated", "Palé actualizado"], "备货库位记录已更新": ["Reserve location updated", "Ubicación actualizada"],
  "任务已完成，库存与历史已更新": ["Task done; stock and history updated", "Tarea finalizada; stock e historial actualizados"],
  "存入完成": ["Put-away completed", "Entrada completada"], "迁移完成": ["Relocation completed", "Traslado completado"],
  "货物已退回原备货库位": ["Stock returned to its reserve location", "Stock devuelto a su ubicación de reserva"],
  "任务历史加载失败": ["Could not load task history", "No se pudo cargar el historial de tareas"],
  "操作历史加载失败": ["Could not load activity", "No se pudo cargar la actividad"],
  "拣货库位加载失败": ["Could not load pick locations", "No se pudieron cargar las ubicaciones de picking"],
  "SKU 数据导入失败": ["SKU import failed", "Error al importar SKU"], "SKU 数据没有变化": ["SKU data unchanged", "Datos SKU sin cambios"],
  "SKU 数据读取失败": ["Could not load SKUs", "No se pudieron cargar los SKU"], "SKU 添加失败": ["Could not add SKU", "No se pudo añadir SKU"],
  "Excel 中没有可导入的 SKU 数据": ["No importable SKUs in Excel", "El Excel no contiene SKU importables"],
  "备库总表导入失败": ["Reserve import failed", "Error al importar reserva"], "备库总表导出失败": ["Reserve export failed", "Error al exportar reserva"],
  "备货统计导出失败": ["Stock summary export failed", "Error al exportar resumen de stock"],
  "仓库台账导入失败": ["Ledger import failed", "Error al importar registro"], "仓库台账导出失败": ["Ledger export failed", "Error al exportar registro"],
  "新增库位失败": ["Could not add location", "No se pudo añadir ubicación"], "更新库位失败": ["Could not update location", "No se pudo actualizar ubicación"],
  "库位批量导入失败": ["Location import failed", "Error al importar ubicaciones"],
  "PDF 作业单打印失败": ["Task PDF print failed", "Error al imprimir PDF de tareas"], "作业单打印失败": ["Task print failed", "Error al imprimir tareas"],
  "当前没有可导出的操作历史": ["No activity to export", "Sin actividad para exportar"],
  "请选择 .xlsx 格式的 WMS_PRODUCT 文件": ["Choose a WMS_PRODUCT .xlsx file", "Elija un archivo WMS_PRODUCT .xlsx"],
  "请选择 .xlsx 格式的仓库台账文件": ["Choose a ledger .xlsx file", "Elija un archivo de registro .xlsx"],
  "请选择 .xlsx 格式的备库总表文件": ["Choose a reserve inventory .xlsx file", "Elija un inventario de reserva .xlsx"],
  "请选择 .xlsx 格式的库位文件": ["Choose a locations .xlsx file", "Elija un archivo de ubicaciones .xlsx"],
  "服务器没有返回台账导入结果": ["Missing ledger import result", "Falta el resultado de importación del registro"],
  "服务器没有返回备库总表导入结果": ["Missing reserve import result", "Falta el resultado de importación de reserva"],
  "服务器没有返回库位导入结果": ["Missing location import result", "Falta el resultado de importación de ubicaciones"],
  "服务器返回了无法识别的数据": ["Invalid server response", "Respuesta del servidor no válida"],
  "服务器返回了空数据": ["Empty server response", "Respuesta vacía del servidor"],
  "{0}小时 {1}分": ["{0}h {1}m", "{0}h {1}m"],
  "波次 {0}": ["Wave {0}", "Ola {0}"], "{0} · 已暂停": ["{0} · Paused", "{0} · En pausa"],
  "确定停用 {0}？": ["Disable {0}?", "¿Desactivar a {0}?"],
  "确定完结波次 {0}？所有进行中的该波次计时会结束。": ["Finish wave {0}? All running timers for this wave will end.", "¿Finalizar la ola {0}? Terminarán todos sus cronómetros activos."],
  "确定中断波次 {0}？正在计时的参与人员将转为在岗待命。": ["Interrupt wave {0}? Active participants will go on standby.", "¿Interrumpir la ola {0}? Los participantes activos quedarán disponibles."],
  "确定移除未开始的波次 {0}？": ["Remove unstarted wave {0}?", "¿Quitar la ola no iniciada {0}?"],
  "确定完结波次 {0}？": ["Finish wave {0}?", "¿Finalizar la ola {0}?"],
  "完结波次 {0} 并切换到 {1}？": ["Finish wave {0} and switch to {1}?", "¿Finalizar la ola {0} y cambiar a {1}?"],
  "确定将任务从 {0} 切换到 {1}？": ["Switch task from {0} to {1}?", "¿Cambiar tarea de {0} a {1}?"],
  "{0} 已提交，请扫描下一位员工": ["{0} submitted. Scan the next employee.", "{0} enviado. Escanee al siguiente empleado."],
  "{0} · {1}已提交": ["{0} · {1} submitted", "{0} · {1} enviado"],
  " · 以下明细将整单提交": [" · All details are submitted together", " · Se envían todos los detalles juntos"],
  " · 最后同步 {0} {1}": [" · Last sync {0} {1}", " · Última sincronización {0} {1}"],
  " · 精确 SKU {0} 个": [" · {0} exact SKUs", " · {0} SKU exactos"],
  "{0} · {1} 条": ["{0} · {1} records", "{0} · {1} registros"],
  "{0} 人参与": ["{0} participants", "{0} participantes"],
  "{0} 人计时": ["{0} working", "{0} trabajando"],
  "{0}，{1}，美东时间": ["{0}, {1}, US Eastern", "{0}, {1}, hora del este"],
  "中断波次并将参与人员转为待命": ["Interrupt wave and place participants on standby", "Interrumpir ola y dejar participantes disponibles"],
  "主库位 {0}": ["Pick location {0}", "Ubicación de picking {0}"],
  "仅勾选的页面会显示在对应主导航或“备货数据”页签中。": ["Only selected pages appear in navigation or stock data tabs.", "Solo las páginas seleccionadas aparecen en el menú o en datos de stock."],
  "休息中": ["Resting", "En descanso"],
  "例如 A-1-001": ["e.g. A-1-001", "Ej.: A-1-001"],
  "例如 A-A-001": ["e.g. A-A-001", "Ej.: A-A-001"],
  "保存中…": ["Saving…", "Guardando…"],
  "保存修改": ["Save changes", "Guardar cambios"],
  "全部权限": ["Full access", "Acceso total"],
  "创建待办": ["Create task", "Crear tarea"],
  "删除账号 · {0}": ["Delete account · {0}", "Eliminar cuenta · {0}"],
  "动作": ["Action", "Acción"],
  "协同 {0} 人：{1}": ["{0} helpers: {1}", "{0} colaboradores: {1}"],
  "取备货 SKU {0}": ["Replenish SKU {0}", "Reponer SKU {0}"],
  "取备货子任务备注 {0}": ["Replenishment note {0}", "Nota de reposición {0}"],
  "取消全选": ["Deselect all", "Quitar selección"],
  "只有正在进行的波次可以中断": ["Only running waves can be interrupted", "Solo se pueden interrumpir olas en curso"],
  "在任务分发中打开 {0}": ["Open {0} in dispatch", "Abrir {0} en asignación"],
  "处理": ["Process", "Procesar"],
  "处理中…": ["Processing…", "Procesando…"],
  "备注说明 {0}": ["Note {0}", "Nota {0}"],
  "备注：{0}": ["Note: {0}", "Nota: {0}"],
  "备注：未填写": ["No note", "Sin nota"],
  "备货库位 {0}": ["Reserve location {0}", "Ubicación de reserva {0}"],
  "存入备货区": ["Put into reserve", "Almacenar en reserva"],
  "完结波次": ["Finish wave", "Finalizar ola"],
  "导入 SKU 数据": ["Import SKUs", "Importar SKU"],
  "导入仓库台账": ["Import ledger", "Importar registro"],
  "导入备库总表": ["Import reserve", "Importar reserva"],
  "尚未导入": ["Not imported", "Sin importar"],
  "尚未开始": ["Not started", "Sin iniciar"],
  "已全部取出": ["All taken", "Retiro completo"],
  "已授权 {0}/{1}": ["Allowed {0}/{1}", "Permisos {0}/{1}"],
  "已退回库位": ["Returned", "Devuelto"],
  "已部分取出": ["Part taken", "Retiro parcial"],
  "库位变化": ["Location change", "Cambio ubicación"],
  "张三\n李四\n王五": ["Alex\nMaria\nDavid", "Alex\nMaría\nDavid"],
  "当前备货库位 {0}": ["Current reserve {0}", "Reserva actual {0}"],
  "当前存放：{0}": ["Currently stored: {0}", "Almacenado: {0}"],
  "当前无人": ["No one currently", "Sin personal ahora"],
  "当前无备货库存": ["No reserve stock", "Sin stock de reserva"],
  "打印PDF作业单": ["Print task PDF", "Imprimir tarea PDF"],
  "打印已选任务": ["Print selected", "Imprimir selección"],
  "扫描操作码或任务条码": ["Scan action or task code", "Escanear código de acción o tarea"],
  "批量任务": ["Batch task", "Tarea en lote"],
  "批量导入库位": ["Import locations", "Importar ubicaciones"],
  "按{0}排序": ["Sort by {0}", "Ordenar por {0}"],
  "搜索{0}或区域": ["Search {0} or zone", "Buscar {0} o zona"],
  "新托盘": ["New pallet", "Nuevo palé"],
  "无协同人员": ["No helpers", "Sin colaboradores"],
  "无备注": ["No note", "Sin nota"],
  "普通": ["Normal", "Normal"],
  "暂无可用备货空位": ["No free reserve slots", "Sin huecos de reserva libres"],
  "暂无记录": ["No records", "Sin registros"],
  "未在 SKU 主数据中找到": ["Not in SKU catalog", "No figura en el catálogo SKU"],
  "权限设置 · {0}": ["Permissions · {0}", "Permisos · {0}"],
  "查看{0}记录": ["View {0} records", "Ver registros de {0}"],
  "正在保存…": ["Saving…", "Guardando…"],
  "正在准备打印…": ["Preparing print…", "Preparando impresión…"],
  "正在创建…": ["Creating…", "Creando…"],
  "正在删除…": ["Deleting…", "Eliminando…"],
  "正在存入…": ["Putting away…", "Almacenando…"],
  "正在导入 {0}%": ["Importing {0}%", "Importando {0}%"],
  "正在导入…": ["Importing…", "Importando…"],
  "正在新增…": ["Adding…", "Añadiendo…"],
  "正在添加…": ["Adding…", "Añadiendo…"],
  "添加 SKU": ["Add SKU", "Añadir SKU"],
  "渠道\t波次号\t类型\tSKU数\t订单数\t件数\nAmazon\tW202608270001\t多件\t24\t80\t126": ["渠道\t波次号\t类型\tSKU数\t订单数\t件数\nAmazon\tW202608270001\t多件\t24\t80\t126", "渠道\t波次号\t类型\tSKU数\t订单数\t件数\nAmazon\tW202608270001\t多件\t24\t80\t126"],
  "目标备货空位 {0}": ["Destination slot {0}", "Hueco destino {0}"],
  "直接操作": ["Direct action", "Acción directa"],
  "确认 · {0}": ["Confirm · {0}", "Confirmar · {0}"],
  "确认删除": ["Confirm delete", "Confirmar borrado"],
  "确认新增{0}": ["Add {0}", "Añadir {0}"],
  "移除第 {0} 条取备货": ["Remove replenishment {0}", "Quitar reposición {0}"],
  "移除第 {0} 条迁移备货": ["Remove relocation {0}", "Quitar traslado {0}"],
  "移除第 {0} 行": ["Remove row {0}", "Quitar fila {0}"],
  "空库位": ["Empty location", "Ubicación vacía"],
  "等待任务": ["Awaiting task", "Sin tarea"],
  "等待员工": ["Awaiting staff", "Esperando empleado"],
  "系统管理员始终拥有全部页面权限，无法取消。": ["Admins always have access to all pages.", "Los administradores siempre tienen acceso a todas las páginas."],
  "系统记录": ["System record", "Registro del sistema"],
  "编辑备货库位记录": ["Edit reserve location", "Editar ubicación de reserva"],
  "编辑托盘记录": ["Edit pallet", "Editar palé"],
  "识别中…": ["Reading…", "Leyendo…"],
  "该 SKU 无可用备货": ["No available stock for this SKU", "Sin stock disponible para este SKU"],
  "该 SKU 无可迁移备货": ["No relocatable stock for this SKU", "Sin stock trasladable para este SKU"],
  "该波次已中断": ["Wave interrupted", "Ola interrumpida"],
  "该波次已经完结": ["Wave already completed", "Ola ya finalizada"],
  "详情": ["Details", "Detalle"],
  "请先输入 SKU": ["Enter a SKU first", "Ingrese primero un SKU"],
  "请先选择当前库位": ["Select the current location first", "Elija primero la ubicación actual"],
  "迁移备货 SKU {0}": ["Relocate SKU {0}", "Trasladar SKU {0}"],
  "选择 {0}": ["Select {0}", "Elegir {0}"],
  "选择任务 {0}": ["Select task {0}", "Elegir tarea {0}"],
  "选择有空位的备货库位": ["Select a reserve location with capacity", "Elija una ubicación de reserva con espacio"],
  "选择空托盘位 {0}": ["Select free slot {0}", "Elegir hueco libre {0}"],
  "选择该 SKU 的备货库位": ["Select this SKU's reserve location", "Elija la ubicación de reserva del SKU"],
  "选择该 SKU 的当前库位": ["Select this SKU's current location", "Elija la ubicación actual del SKU"],
  "内库": ["内库", "内库"],
  "备货操作": ["Stock tasks", "Preparación"],
  "备库总表": ["Reserve stock", "Inventario"],
  "备货待办": ["Stock queue", "Pendientes"],
  "备货数据": ["Stock data", "Datos de stock"],
  "待办任务": ["Tasks", "Tareas"],
  "SKU管理": ["SKU catalog", "Catálogo SKU"],
  "库位管理": ["Locations", "Ubicaciones"],
  "仓库台账": ["Stock ledger", "Movimientos"],
  "任务分发": ["Dispatch", "Asignación"],
  "工卡扫描": ["Card scan", "Escanear"],
  "现场看板": ["Live board", "Panel en vivo"],
  "工作记录": ["Work records", "Registro laboral"],
  "员工数据": ["Employees", "Personal"],
  "员工状态": ["Staff status", "Estado laboral"],
  "备货体系": ["STOCK", "INVENTARIO"],
  "工时体系": ["WORKFORCE", "PERSONAL"],
  "账户管理": ["Accounts", "Cuentas"],
  "美东时间": ["US Eastern", "Este de EE. UU."],
  "系统时间为美东时间": ["Times use US Eastern time", "Horario del este de EE. UU."],
  "管理员": ["Admin", "Admin"],
  "普通用户": ["User", "Usuario"],
  "退出登录": ["Sign out", "Salir"],
  "账号": ["Account", "Cuenta"],
  "密码": ["Password", "Clave"],
  "账号名称": ["Username", "Usuario"],
  "初始密码": ["Initial password", "Clave inicial"],
  "请输入内部账号": ["Enter your username", "Ingrese su usuario"],
  "请输入密码": ["Enter your password", "Ingrese su clave"],
  "进入内库": ["Welcome", "Bienvenido"],
  "登录系统": ["Sign in", "Entrar"],
  "正在登录…": ["Signing in…", "Ingresando…"],
  "登录失败，请重试": ["Sign-in failed. Try again.", "No se pudo ingresar. Reintente."],
  "登录已失效": ["Session expired", "Sesión vencida"],
  "账号或密码错误": ["Invalid username or password", "Usuario o clave incorrectos"],
  "内部系统 · 账号与页面权限由管理员配置": ["Internal use · Admin-managed access", "Uso interno · Acceso administrado"],
  "看见每一次流转，": ["Track every move.", "Siga cada movimiento."],
  "掌握每一班工况。": ["Know every shift.", "Conozca cada turno."],
  "连接货物、库位、任务与人员，让仓内备货过程可追踪、作业状态可掌握、协同处置更清晰。": ["Connect stock, locations, tasks and people. Track warehouse movements and keep teams coordinated.", "Conecte mercancía, ubicaciones, tareas y personal. Controle movimientos y coordine al equipo."],
  "查看仓内流转、作业任务与人员工况": ["Track stock, tasks and team activity", "Stock, tareas y actividad del equipo"],
  "货物流转": ["Stock flow", "Flujo de stock"],
  "全程可追": ["Traceable", "Trazable"],
  "人员工况": ["Team activity", "Actividad"],
  "状态清晰": ["Clear status", "Estado claro"],
  "仓内协同": ["Coordination", "Coordinación"],
  "任务闭环": ["Task tracking", "Seguimiento"],
  "系统能力": ["Capabilities", "Funciones"],
  "保存": ["Save", "Guardar"],
  "取消": ["Cancel", "Cancelar"],
  "关闭": ["Close", "Cerrar"],
  "删除": ["Delete", "Borrar"],
  "修改": ["Edit", "Editar"],
  "编辑": ["Edit", "Editar"],
  "重试": ["Retry", "Reintentar"],
  "重置": ["Reset", "Restablecer"],
  "清空": ["Clear", "Limpiar"],
  "导入": ["Import", "Importar"],
  "导出": ["Export", "Exportar"],
  "搜索": ["Search", "Buscar"],
  "操作": ["Actions", "Acciones"],
  "状态": ["Status", "Estado"],
  "类型": ["Type", "Tipo"],
  "全部": ["All", "Todos"],
  "全选": ["Select all", "Todos"],
  "当前": ["Current", "Actual"],
  "日期": ["Date", "Fecha"],
  "姓名": ["Name", "Nombre"],
  "渠道": ["Channel", "Canal"],
  "负责人": ["Lead", "Titular"],
  "订单": ["Orders", "Pedidos"],
  "件数": ["Units", "Unidades"],
  "波次号": ["Wave", "Ola"],
  "波次工时": ["Wave time", "Horas ola"],
  "时效": ["Units/h", "Unid./h"],
  "开始时间": ["Started", "Inicio"],
  "完结时间": ["Completed", "Fin"],
  "开始日期": ["Start date", "Fecha inicial"],
  "结束日期": ["End date", "Fecha final"],
  "起始日期": ["From", "Desde"],
  "终止日期": ["To", "Hasta"],
  "时长": ["Duration", "Duración"],
  "前一天": ["Previous", "Anterior"],
  "后一天": ["Next", "Siguiente"],
  "上一页": ["Previous", "Anterior"],
  "下一页": ["Next", "Siguiente"],
  "‹ 上一月": ["‹ Prev. month", "‹ Mes anterior"],
  "下一月 ›": ["Next month ›", "Mes siguiente ›"],
  "‹ 返回列表": ["‹ Back", "‹ Volver"],
  "返回列表": ["Back to list", "Volver a lista"],
  "☰ 菜单": ["☰ Menu", "☰ Menú"],
  "✕ 关闭菜单": ["✕ Close menu", "✕ Cerrar menú"],
  "打开页面菜单": ["Open menu", "Abrir menú"],
  "关闭页面菜单": ["Close menu", "Cerrar menú"],
  "正在读取仓库数据": ["Loading stock data", "Cargando inventario"],
  "数据加载失败": ["Unable to load data", "No se pudieron cargar los datos"],
  "重新加载": ["Reload", "Recargar"],
  "备货核心操作": ["Stock operations", "Operaciones de stock"],
  "存备货": ["Put away", "Almacenar"],
  "取备货": ["Replenish", "Reponer"],
  "迁移备货": ["Relocate", "Trasladar"],
  "批量入库": ["Bulk put-away", "Entrada en lote"],
  "供给拣货位": ["Fill pick locations", "Reponer picking"],
  "库内移位": ["Move within stock", "Traslado interno"],
  "备货库存": ["Reserve stock", "Stock reserva"],
  "当前有效托盘": ["Active pallets", "Palés activos"],
  "托盘位占用": ["Space usage", "Ocupación"],
  "今日已处理托盘": ["Handled today", "Procesados hoy"],
  "今日已确认作业结果": ["Confirmed today", "Confirmados hoy"],
  "查看全部 →": ["View all →", "Ver todo →"],
  "最近操作历史": ["Recent activity", "Actividad reciente"],
  "操作历史": ["History", "Historial"],
  "操作记录": ["Activity", "Actividad"],
  "全部操作记录": ["All activity", "Toda la actividad"],
  "备库托盘与库位总表": ["Reserve pallets and locations", "Palés y ubicaciones de reserva"],
  "多个 SKU（精确）": ["Multiple SKUs (exact)", "Varios SKU (exactos)"],
  "精确搜索多个 SKU": ["Exact search for multiple SKUs", "Buscar varios SKU exactos"],
  "逗号、分号或换行分隔": ["Separate with commas, semicolons or lines", "Separar con comas, punto y coma o saltos de línea"],
  "导出已选": ["Export selected", "Exportar selección"],
  "全选当前筛选结果": ["Select all filtered rows", "Seleccionar todas las filas filtradas"],
  "⇩ 导出备货统计": ["⇩ Stock summary", "⇩ Resumen de stock"],
  "批量取备货": ["Bulk replenishment", "Reposición en lote"],
  "批量迁移": ["Bulk relocation", "Traslado en lote"],
  "库存状态": ["Stock status", "Estado de stock"],
  "全部状态": ["All states", "Todos los estados"],
  "在库": ["In stock", "En stock"],
  "作业中": ["In progress", "En proceso"],
  "空托盘位": ["Free slots", "Huecos libres"],
  "当前货物：": ["Stock: ", "Stock: "],
  "当前托盘": ["Current pallet", "Palé actual"],
  "入库时间（美东）": ["Received (ET)", "Entrada (ET)"],
  "备库 SKU 搜索": ["Reserve SKU search", "Buscar SKU en reserva"],
  "搜索 SKU": ["Search SKU", "Buscar SKU"],
  "输入 SKU 模糊搜索": ["Enter part of a SKU", "Ingrese parte del SKU"],
  "清除 SKU 搜索": ["Clear SKU search", "Limpiar búsqueda SKU"],
  "手机端搜索 SKU": ["Mobile SKU search", "Buscar SKU en móvil"],
  "模糊搜索 SKU": ["Partial SKU search", "Buscar SKU parcial"],
  "备货库位": ["Reserve loc.", "Ubic. reserva"],
  "拣货库位": ["Pick loc.", "Ubic. picking"],
  "库位": ["Location", "Ubicación"],
  "主库位": ["Pick loc.", "Ubic. picking"],
  "起始库位": ["Source", "Origen"],
  "目标备货库位": ["Destination", "Destino"],
  "备货库位 / 起始库位": ["Reserve / source", "Reserva / origen"],
  "主库位 / 目标库位": ["Pick / destination", "Picking / destino"],
  "备货库位 / 托盘": ["Reserve / pallet", "Reserva / palé"],
  "备货库位 / 托盘 *": ["Reserve / pallet *", "Reserva / palé *"],
  "当前备货库位 / 托盘": ["Current reserve / pallet", "Reserva actual / palé"],
  "当前备货库位 / 托盘 *": ["Current reserve / pallet *", "Reserva actual / palé *"],
  "主库位 *": ["Pick loc. *", "Ubic. picking *"],
  "备货库位 *": ["Reserve loc. *", "Ubic. reserva *"],
  "目标备货空位": ["Free destination", "Destino libre"],
  "目标备货空位 *": ["Free destination *", "Destino libre *"],
  "备注": ["Note", "Nota"],
  "备注 *": ["Note *", "Nota *"],
  "备注：": ["Note: ", "Nota: "],
  "备注说明": ["Notes", "Notas"],
  "备注说明：": ["Notes: ", "Notas: "],
  "子任务": ["Subtask", "Subtarea"],
  "子任务备注": ["Subtask note", "Nota de subtarea"],
  "子任务备注：": ["Subtask note: ", "Nota de subtarea: "],
  "必填": ["Required", "Obligatorio"],
  "选填": ["Optional", "Opcional"],
  "选填：填写本托作业注意事项": ["Optional pallet instructions", "Instrucciones opcionales del palé"],
  "输入 SKU": ["Enter SKU", "Ingrese SKU"],
  "输入或选择 SKU": ["Enter or select SKU", "Ingrese o elija SKU"],
  "输入或选择主库位": ["Enter or select pick location", "Ingrese o elija ubicación de picking"],
  "选择库位": ["Select location", "Elegir ubicación"],
  "搜索库位": ["Search locations", "Buscar ubicaciones"],
  "模糊搜索库位": ["Partial location search", "Buscar ubicación parcial"],
  "全部取出": ["Take all", "Retirar todo"],
  "部分取出": ["Take part", "Retiro parcial"],
  "退回库位": ["Return", "Devolver"],
  "退回备货位": ["Return to reserve", "Devolver a reserva"],
  "退回": ["Return", "Devolver"],
  "完成迁移": ["Move done", "Traslado listo"],
  "完成入库": ["Put-away done", "Entrada lista"],
  "全部完成": ["Complete all", "Completar todo"],
  "作业结果": ["Outcome", "Resultado"],
  "处理结果": ["Outcome", "Resultado"],
  "选择处理结果": ["Select outcome", "Elegir resultado"],
  "待处理": ["Pending", "Pendiente"],
  "已处理": ["Processed", "Procesado"],
  "已取消": ["Cancelled", "Cancelado"],
  "已退回": ["Returned", "Devuelto"],
  "当前没有待处理任务": ["No pending tasks", "No hay tareas pendientes"],
  "暂无已处理任务": ["No processed tasks", "No hay tareas procesadas"],
  "该待办已被处理或已不再可用。": ["This task is processed or no longer available.", "Esta tarea ya fue procesada o no está disponible."],
  "请先选择处理结果": ["Select an outcome first", "Elija un resultado"],
  "正在提交…": ["Submitting…", "Enviando…"],
  "提交中": ["Sending", "Enviando"],
  "紧急": ["Urgent", "Urgente"],
  "备货任务状态": ["Stock task status", "Estado de tareas"],
  "全选待处理任务": ["Select pending tasks", "Seleccionar pendientes"],
  "任务 / 子任务": ["Task / subtask", "Tarea / subtarea"],
  "任务 / 操作人": ["Task / operator", "Tarea / operador"],
  "托盘号": ["Pallet", "Palé"],
  "托盘号：": ["Pallet: ", "Palé: "],
  "托盘参考": ["Pallet ref.", "Ref. palé"],
  "托盘参考：": ["Pallet ref.: ", "Ref. palé: "],
  "起始库位：": ["Source: ", "Origen: "],
  "备货库位：": ["Reserve: ", "Reserva: "],
  "主库位：": ["Pick location: ", "Picking: "],
  "· 目标库位：": ["· Destination: ", "· Destino: "],
  "手动添加 SKU": ["Add SKU", "Añadir SKU"],
  "＋ 手动添加 SKU": ["＋ Add SKU", "＋ Añadir SKU"],
  "产品名称": ["Product", "Producto"],
  "产品条码": ["Barcode", "Código de barras"],
  "客户": ["Client", "Cliente"],
  "申报中文名": ["Chinese declaration", "Nombre declarado en chino"],
  "有效产品记录": ["Active products", "Productos activos"],
  "最近更新（美东）": ["Updated (ET)", "Actualizado (ET)"],
  "搜索 SKU 主数据": ["Search SKU catalog", "Buscar catálogo SKU"],
  "搜索 SKU、产品条码、客户、产品名称或申报中文名": ["Search SKU, barcode, client or product name", "Buscar SKU, código, cliente o producto"],
  "WMS 产品主数据用于核对备货区 SKU；未收录的在库 SKU 会以红色显示。": ["The WMS catalog validates reserve SKUs. Unlisted stocked SKUs appear in red.", "El catálogo WMS valida los SKU de reserva. Los SKU no registrados aparecen en rojo."],
  "SKU 为必填项，系统会忽略大小写校验重复；其余信息可选填。": ["SKU is required and checked without case sensitivity. Other fields are optional.", "SKU obligatorio; los duplicados se validan sin distinguir mayúsculas. Los demás campos son opcionales."],
  "库位类型": ["Location type", "Tipo de ubicación"],
  "库位编码": ["Location code", "Código ubicación"],
  "托盘容量": ["Capacity", "Capacidad"],
  "区域": ["Zone", "Zona"],
  "当前新增类型": ["New location type", "Nuevo tipo"],
  "同名的另一类型库位不会被覆盖": ["Same-name locations of other types stay unchanged", "No se sobrescriben ubicaciones de otro tipo con el mismo nombre"],
  "库位类型是身份的一部分，不能在此转换为拣货库位": ["Location type cannot be changed here", "El tipo de ubicación no se puede cambiar aquí"],
  "备货库位与拣货库位独立管理；即使名称相同，也属于两个不同库位。": ["Reserve and pick locations are separate, even if their names match.", "Reserva y picking son ubicaciones distintas aunque compartan nombre."],
  "默认取编码首段": ["Defaults to code prefix", "Por defecto, prefijo del código"],
  "当前占用": ["Occupied", "Ocupado"],
  "已占用": ["Occupied", "Ocupado"],
  "可用": ["Available", "Disponible"],
  "⇩ 下载 Excel 模板": ["⇩ Excel template", "⇩ Plantilla Excel"],
  "⇩ 导出全部库位": ["⇩ Export locations", "⇩ Exportar ubicaciones"],
  "⇩ 导出全部台账": ["⇩ Export ledger", "⇩ Exportar registro"],
  "SKU 台账": ["SKU ledger", "Registro SKU"],
  "库位台账": ["Location ledger", "Registro ubicación"],
  "仓库台账分类": ["Ledger category", "Categoría de registro"],
  "完整记录 SKU、库位与每一次托盘移动": ["Full SKU, location and pallet movement history", "Historial completo de SKU, ubicaciones y movimientos"],
  "SKU 完整流转": ["SKU movement history", "Historial del SKU"],
  "库位完整历史 ·": ["Location history ·", "Historial ubicación ·"],
  "同名 SKU 记录": ["Matching SKU records", "Registros del mismo SKU"],
  "历史 SKU": ["Historical SKUs", "SKU históricos"],
  "唯一 SKU": ["Unique SKUs", "SKU únicos"],
  "有记录库位": ["Recorded locations", "Ubicaciones registradas"],
  "移动路径": ["Movement", "Trayecto"],
  "区内迁移": ["Internal move", "Traslado interno"],
  "台账动作": ["Ledger action", "Acción de registro"],
  "全部动作": ["All actions", "Todas las acciones"],
  "入库日期": ["Received", "Entrada"],
  "入库开始日期": ["Received from", "Entrada desde"],
  "入库结束日期": ["Received until", "Entrada hasta"],
  "移入记录": ["Inbound", "Entradas"],
  "移出记录": ["Outbound", "Salidas"],
  "权限范围": ["Permissions", "Permisos"],
  "子页面权限": ["Page access", "Acceso a páginas"],
  "保存权限": ["Save access", "Guardar permisos"],
  "点击管理": ["Manage", "Gestionar"],
  "创建账号": ["Create account", "Crear cuenta"],
  "＋ 新增内部账号": ["＋ Add account", "＋ Añadir cuenta"],
  "该账号将立即无法登录，所有已登录会话也会失效。仓库操作历史会保留原操作人信息。": ["This account will lose access immediately, including active sessions. Operator history will be retained.", "La cuenta perderá acceso inmediato, incluidas sus sesiones activas. Se conservará el historial del operador."],
  "管理员默认拥有全部权限。普通账号只会看到被授权的子页面；新增页面默认不授权，已删除页面的旧权限自动失效。": ["Admins have all access. Other accounts see only authorized pages. New pages require permission; removed pages lose access automatically.", "Los administradores tienen acceso total. Otras cuentas solo ven páginas autorizadas. Las nuevas requieren permiso; las eliminadas pierden acceso."],
  "工时体系页面": ["Workforce pages", "Páginas de personal"],
  "备货数据页签": ["Stock data tabs", "Pestañas de stock"],
  "新增员工": ["Add staff", "Añadir personal"],
  "编辑员工": ["Edit employee", "Editar empleado"],
  "新增并分配 ID": ["Add and assign ID", "Añadir y asignar ID"],
  "组织类型": ["Organization", "Organización"],
  "职能": ["Default task", "Función"],
  "未设置": ["Not set", "Sin asignar"],
  "员工姓名（每行一人）": ["Names (one per line)", "Nombres (uno por línea)"],
  "员工 ID、姓名、组织或职能": ["ID, name, organization or task", "ID, nombre, organización o función"],
  "搜索员工": ["Search staff", "Buscar personal"],
  "在职": ["Active", "Activo"],
  "已停用": ["Disabled", "Inactivo"],
  "已启用": ["Enabled", "Activo"],
  "停用": ["Disable", "Desactivar"],
  "启用": ["Enable", "Activar"],
  "考勤导出": ["Attendance", "Asistencia"],
  "导出扫描素材": ["Export badges", "Exportar tarjetas"],
  "正在生成…": ["Generating…", "Generando…"],
  "正在导出…": ["Exporting…", "Exportando…"],
  "导出 Excel": ["Export Excel", "Exportar Excel"],
  "导出范围": ["Export range", "Rango a exportar"],
  "自然月": ["Month", "Mes"],
  "整个自然月": ["Full month", "Mes completo"],
  "上半月（1–15日）": ["First half (1–15)", "Primera mitad (1–15)"],
  "下半月（16日–月末）": ["Second half (16–end)", "Segunda mitad (16–fin)"],
  "首个 Sign In": ["First sign-in", "Primera entrada"],
  "最后 Sign Out": ["Last sign-out", "Última salida"],
  "当天不在岗": ["Off-duty today", "Ausencia de hoy"],
  "今日在岗": ["On duty today", "Presencia hoy"],
  "今日工作": ["Work today", "Trabajo hoy"],
  "当前状态": ["Current status", "Estado actual"],
  "当前任务": ["Current task", "Tarea actual"],
  "在岗": ["On duty", "Trabajando"],
  "待命": ["Standby", "Disponible"],
  "在岗待命": ["Standby", "Disponible"],
  "工作中": ["Working", "Trabajando"],
  "不在岗": ["Off duty", "Fuera de turno"],
  "已下班": ["Off duty", "Fuera de turno"],
  "休息": ["Rest", "Descanso"],
  "未上班": ["Not started", "Sin iniciar"],
  "进行中": ["Active", "En curso"],
  "未开始": ["Not started", "Sin iniciar"],
  "未开启": ["Not started", "Sin iniciar"],
  "中断": ["Interrupted", "Interrumpida"],
  "暂停": ["Paused", "Pausa"],
  "已暂停": ["Paused", "En pausa"],
  "已完成": ["Done", "Finalizada"],
  "完结": ["Finish", "Finalizar"],
  "移除": ["Remove", "Quitar"],
  "完结当前波次": ["Finish wave", "Finalizar ola"],
  "Sign In": ["Sign In", "Entrada"],
  "Sign Out": ["Sign Out", "Salida"],
  "Confirm": ["Confirm", "Confirmar"],
  "上班 / Sign In": ["Sign In", "Entrada"],
  "下班 / Sign Out": ["Sign Out", "Salida"],
  "确认 / CONFIRM": ["CONFIRM", "CONFIRMAR"],
  "确认": ["Confirm", "Confirmar"],
  "切换员工": ["Switch staff", "Cambiar persona"],
  "扫描员工卡": ["Scan employee card", "Escanear tarjeta"],
  "扫描内容": ["Scanned code", "Código leído"],
  "识别中": ["Reading", "Leyendo"],
  "自动识别": ["Auto scan", "Lectura auto."],
  "扫描员工后显示": ["Scan a card first", "Escanee una tarjeta"],
  "扫描员工后可用": ["Scan a card first", "Escanee una tarjeta"],
  "暂无任务": ["No task", "Sin tarea"],
  "主负责人": ["Lead", "Titular"],
  "协作人员": ["Helper", "Colaborador"],
  "请先选择操作或任务": ["Choose an action or task", "Elija una acción o tarea"],
  "选择任务": ["Choose task", "Elegir tarea"],
  "固定任务": ["Fixed tasks", "Tareas fijas"],
  "只有在岗员工可以开始计时": ["Only on-duty staff can start work", "Solo el personal en turno puede iniciar tareas"],
  "暂无固定任务": ["No fixed tasks", "No hay tareas fijas"],
  "暂无当前波次": ["No current waves", "No hay olas actuales"],
  "今日记录": ["Today's log", "Registro de hoy"],
  "今日操作": ["Today's activity", "Actividad de hoy"],
  "今天尚无操作记录": ["No activity today", "Sin actividad hoy"],
  "扫描员工后显示当天记录": ["Scan a card to see today's log", "Escanee una tarjeta para ver el registro de hoy"],
  "导入波次": ["Import waves", "Importar olas"],
  "导入当前波次": ["Import current waves", "Importar olas actuales"],
  "当前波次": ["Current waves", "Olas actuales"],
  "工作汇总": ["Work summary", "Resumen laboral"],
  "导出筛选结果": ["Export filtered", "Exportar filtro"],
  "参与过的波次": ["Participated waves", "Olas con participación"],
  "员工统计": ["Staff", "Personal"],
  "员工总数": ["Total staff", "Total personal"],
  "工时统计": ["Work hours", "Horas"],
  "在岗时长": ["On duty", "Presencia"],
  "工作时长": ["Working", "Trabajo"],
  "拣货": ["Picking", "Picking"],
  "仓务": ["Warehouse", "Almacén"],
  "混件扫描": ["Mixed scan", "Escaneo mixto"],
  "单件扫描": ["Single scan", "Escaneo simple"],
  "问题单": ["Exceptions", "Incidencias"],
  "清洁": ["Cleaning", "Limpieza"],
  "波次状态": ["Wave status", "Estado de olas"],
  "波次数量": ["Waves", "Olas"],
  "完成情况": ["Completed", "Finalizado"],
  "单量总数": ["Orders", "Pedidos"],
  "拣货件数": ["Units picked", "Unidades"],
  "多件订单": ["Multi orders", "Pedidos multi"],
  "混件订单": ["Mixed orders", "Pedidos mixtos"],
  "已完成波次": ["Completed waves", "Olas finalizadas"],
  "现场统计": ["Live statistics", "Estadísticas"],
  "当前筛选下暂无员工": ["No matching staff", "Sin personal coincidente"],
  "当前筛选下暂无波次": ["No matching waves", "Sin olas coincidentes"],
  "协同人员 ·": ["Helpers ·", "Colaboradores ·"],
  "仅用于导出": ["Export only", "Solo exportación"],
  "导出日期范围": ["Export date range", "Fechas de exportación"],
  "导出起始日期": ["Export start date", "Fecha inicial de exportación"],
  "导出终止日期": ["Export end date", "Fecha final de exportación"],
  "粘贴制表符或逗号分隔的波次数据": ["Paste tab- or comma-separated wave data", "Pegue datos de olas separados por tabulaciones o comas"],
  "尚未识别到可导入的波次": ["No valid waves found", "No se encontraron olas válidas"],
  "工卡扫描仅供移动终端使用": ["Card scanning is for mobile devices", "Escaneo disponible en dispositivos móviles"],
  "请使用 iPhone、iPad 或其他带摄像头的触控终端打开本页面。": ["Open this page on an iPhone, iPad or touch device with a camera.", "Abra esta página en un iPhone, iPad u otro dispositivo táctil con cámara."],
  "工卡扫描摄像头画面": ["Card scanner camera", "Cámara del escáner"],
  "正在读取员工信息": ["Loading employee", "Cargando empleado"],
  "点击扫描开启摄像头": ["Tap Scan to open the camera", "Pulse Escanear para abrir la cámara"],
  "提示音": ["Sound on", "Con sonido"],
  "已静音": ["Muted", "Sin sonido"],
  "关闭扫描成功提示音": ["Mute scan sound", "Silenciar aviso de escaneo"],
  "开启扫描成功提示音": ["Enable scan sound", "Activar aviso de escaneo"],
  "扫描中": ["Scanning", "Escaneando"],
  "扫描": ["Scan", "Escanear"],
  "读取中…": ["Loading…", "Cargando…"],
  "尚未识别员工": ["No employee scanned", "Sin empleado identificado"],
  "考勤操作": ["Attendance actions", "Acciones de asistencia"],
  "当天处理内容": ["Daily activity", "Actividad del día"],
  "今天没有考勤或工作记录": ["No attendance or work today", "Sin asistencia ni trabajo hoy"],
  "员工的 Sign In、Sign Out 和工作内容会显示在这里": ["Sign-ins, sign-outs and work appear here", "Aquí aparecen entradas, salidas y tareas"],
  "请扫描员工卡": ["Please scan a card", "Escanee una tarjeta"],
  "每页展示一个完整自然月。": ["Each page shows a full calendar month.", "Cada página muestra un mes completo."],
  "自然月记录": ["Monthly record", "Registro mensual"],
  "自然月在岗记录": ["Monthly attendance", "Asistencia mensual"],
  "导出整月 PDF": ["Monthly PDF", "PDF mensual"],
  "导出整月数据": ["Monthly export", "Exportar mes"],
  "出勤天数": ["Days worked", "Días trabajados"],
  "本月总工时": ["Monthly hours", "Horas del mes"],
  "上半月工时": ["First-half hours", "Horas 1.ª mitad"],
  "下半月工时": ["Second-half hours", "Horas 2.ª mitad"],
  "星期": ["Weekday", "Día"],
  "性质": ["Kind", "Clase"],
  "内容": ["Details", "Detalle"],
  "考勤": ["Attendance", "Asistencia"],
  "波次": ["Wave", "Ola"],
  "日常": ["Routine", "Rutina"],
  "开始—结束": ["Start–end", "Inicio–fin"],
  "时间（美东）": ["Time (ET)", "Hora (ET)"],
  "新时间": ["New time", "Nueva hora"],
  "· 原时间": ["· Previous time", "· Hora anterior"],
  "时间修改日志": ["Time edit log", "Cambios de hora"],
  "请填写修改原因": ["Enter the reason for this edit", "Indique el motivo del cambio"],
  "当天没有时间修改记录。": ["No time edits on this date.", "Sin cambios de hora en esta fecha."],
  "没有考勤或工作记录": ["No attendance or work records", "Sin registros de asistencia o trabajo"],
  "全屏展示": ["Full screen", "Pantalla completa"],
  "员工状态卡片": ["Employee status cards", "Tarjetas de estado"],
  "暂无启用的员工": ["No active employees", "No hay empleados activos"],
  "重新打开登录页面": ["Return to sign-in", "Volver al inicio de sesión"],
  "自动同步中": ["Syncing", "Sincronizando"],
  "正在读取员工状态": ["Loading staff status", "Cargando estado del personal"],
  "自动同步已暂停 · 每日 07:00–22:00": ["Sync paused · Daily 07:00–22:00", "Sincronización pausada · Diario 07:00–22:00"],
  "连接异常，数据可能已过期": ["Connection issue; data may be outdated", "Problema de conexión; los datos pueden estar desactualizados"],
  "登录已失效，请重新登录": ["Session expired. Sign in again.", "Sesión vencida. Ingrese de nuevo."],
  "员工状态访问权限已被取消": ["Staff status access was revoked", "Se retiró el permiso para ver el estado del personal"],
  "无法进入全屏，请使用浏览器的全屏功能。": ["Use your browser's full-screen option.", "Use la opción de pantalla completa del navegador."],
  "提交失败，请重试": ["Submit failed. Try again.", "No se pudo enviar. Reintente."],
  "操作失败": ["Action failed", "Error al realizar la acción"],
  "服务器响应超时，请重新加载": ["Server timeout. Please reload.", "El servidor tardó demasiado. Recargue la página."],
  "＋ 新增": ["＋ Add", "＋ Añadir"],
  "＋ 添加一行": ["＋ Add row", "＋ Añadir fila"],
  "＋ 添加一条取备货": ["＋ Add replenishment", "＋ Añadir reposición"],
  "＋ 添加一条迁移备货": ["＋ Add relocation", "＋ Añadir traslado"],
  "请填写每一行的 SKU 后再存入备货区。": ["Enter a SKU on every row before putting stock away.", "Ingrese un SKU en cada fila antes de almacenar."],
  "每行先输入 SKU，再选择该 SKU 当前所在的备货库位和托盘，最后从仍有空托盘位的备货库位中选择迁移目标。": ["For each row, enter the SKU, select its reserve location and pallet, then choose a destination with free capacity.", "En cada fila, ingrese el SKU, elija su ubicación y palé y seleccione un destino con espacio libre."],
  "每行选择 SKU、备货托盘和主库位，可填写独立备注；每行将创建一个独立的取备货待办。": ["Select a SKU, reserve pallet and pick location per row. Each row creates a separate task with an optional note.", "Elija SKU, palé y ubicación de picking por fila. Cada fila crea una tarea independiente con nota opcional."],
  "可先添加多行再统一填写。同一库位可按托盘容量分配多行；每行的 SKU 和备货库位为必填，备注说明选填。": ["Add rows, then fill them in. Each row requires a SKU and reserve location. Notes are optional; location capacity applies.", "Añada filas y complételas. Cada fila requiere SKU y ubicación de reserva. Notas opcionales; se respeta la capacidad."],
  "! 当前没有可分配的目标库位": ["! No available destination", "! Sin destino disponible"],
  "已达到当前可用备货托盘数量。": ["All available reserve pallets are selected.", "Todos los palés de reserva disponibles están seleccionados."],
  "已达到当前备货区空托盘位数量。": ["All free reserve slots are allocated.", "Todos los huecos libres de reserva están asignados."],
  "备货库位已满，无法继续添加。": ["This reserve location is full.", "Esta ubicación de reserva está llena."],
  "未标注 SKU": ["No SKU", "Sin SKU"],
  "收货暂存区": ["Receiving area", "Zona de recepción"],
  "待分配": ["Unassigned", "Sin asignar"],
  "托": ["plt", "palés"],
  "件": ["units", "unid."],
  "人": ["staff", "pers."],
  "天": ["days", "días"],
  "条": ["rows", "filas"],
  "项": ["items", "elem."],
  "页": ["pages", "pág."],
  "共": ["Total", "Total"],
  "第": ["Page", "Pág."],
  "已选": ["Selected", "Selección"],
  "找到": ["Found", "Resultados"],
  "每页": ["Per page", "Por página"],
  "每页最多": ["Per page, max.", "Máx. por página"],
  "还有": ["Plus", "Más"],
  "另有": ["Plus", "Más"],
  "个库位": ["locations", "ubicaciones"],
  "个波次": ["waves", "olas"],
  "名员工": ["employees", "empleados"],
  "条记录": ["records", "registros"],
  "项筛选": ["filters", "filtros"],
  "条明细 · 整单处理": ["details · processed together", "detalles · procesamiento conjunto"],
  "个待处理任务": ["pending tasks", "tareas pendientes"],
  "个 · 第": ["items · Page", "elementos · Pág."],
  "条 · 第": ["rows · Page", "filas · Pág."],
  "托在库": ["pallets in stock", "palés en stock"],
  "托在库 ·": ["pallets in stock ·", "palés en stock ·"],
  "单 /": ["orders /", "pedidos /"],
  "个托盘位，当前": ["slots; currently", "huecos; actualmente"],
  "（余": ["(free", "(libres"],
  "（可用": ["(available", "(disponibles"],
  "（空位": ["(free slots", "(huecos libres"],
  "当前波次及": ["Current waves and", "Olas actuales y"],
  "按时间倒序，当前显示": ["Newest first; showing", "Más recientes primero; mostrando"],
  "显示今天全部操作记录，共": ["All activity today; total", "Actividad de hoy; total"],
  "包含今日及前一天的全部操作记录，共": ["All activity today and yesterday; total", "Actividad de hoy y ayer; total"],
  "确定删除账号“": ["Delete account “", "¿Eliminar la cuenta “"],
  "”吗？": ["”?", "”?"],
};

export function translate(language: Language, source: string, values: Record<string, string | number | null | undefined> = {}): string {
  const template = language === "zh" ? source : messages[source]?.[language === "en" ? 0 : 1] ?? source;
  return template.replace(/\{(\d+)\}/g, (token, key: string) => Object.hasOwn(values, key) ? String(values[key]) : token);
}
