import { getPool } from "./index";

let schemaInitialization:Promise<void>|null=null;
const POSTGRES_RUNTIME_SCHEMA_VERSION=1001;
const SCHEMA_LOCK="aws-miniflow-neiku-schema";

export function ensureRuntimeSchema() {
  schemaInitialization??=initializeRuntimeSchema().catch(error=>{
    schemaInitialization=null;
    throw error;
  });
  return schemaInitialization;
}

async function initializeRuntimeSchema() {
  const client=await getPool().connect();
  try {
    await client.query("SELECT pg_advisory_lock(hashtext($1))",[SCHEMA_LOCK]);
    await client.query("BEGIN");
    await client.query(`
      CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email TEXT NOT NULL UNIQUE,
        username TEXT NOT NULL UNIQUE,
        name TEXT NOT NULL,
        password_hash TEXT NOT NULL,
        password_salt TEXT NOT NULL,
        role TEXT NOT NULL DEFAULT 'operator' CHECK (role IN ('admin','manager','operator')),
        active BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
      CREATE TABLE IF NOT EXISTS sessions (
        id TEXT PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        expires_at TIMESTAMPTZ NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
      CREATE TABLE IF NOT EXISTS locations (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        code TEXT NOT NULL,
        type TEXT NOT NULL CHECK (type IN ('reserve','pick')),
        zone TEXT NOT NULL,
        capacity INTEGER NOT NULL DEFAULT 1 CHECK (capacity BETWEEN 1 AND 999),
        status TEXT NOT NULL DEFAULT 'available' CHECK (status IN ('available','occupied'))
      );
      CREATE TABLE IF NOT EXISTS skus (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        code TEXT NOT NULL UNIQUE,
        unit TEXT NOT NULL DEFAULT '箱',
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
      CREATE TABLE IF NOT EXISTS sku_catalog (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        code TEXT NOT NULL,
        barcode TEXT NOT NULL DEFAULT '',
        client TEXT NOT NULL DEFAULT '',
        product_name TEXT NOT NULL DEFAULT '',
        declared_chinese_name TEXT NOT NULL DEFAULT '',
        source_row INTEGER NOT NULL,
        import_key TEXT NOT NULL,
        active BOOLEAN NOT NULL DEFAULT FALSE,
        imported_at TIMESTAMPTZ NOT NULL
      );
      CREATE TABLE IF NOT EXISTS pallets (
        id TEXT PRIMARY KEY,
        sku_id INTEGER NOT NULL REFERENCES skus(id),
        location_id INTEGER REFERENCES locations(id),
        remarks TEXT NOT NULL DEFAULT '',
        status TEXT NOT NULL DEFAULT 'in_stock' CHECK (status IN ('in_stock','in_task','depleted')),
        inbound_at TIMESTAMPTZ NOT NULL,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
      CREATE TABLE IF NOT EXISTS tasks (
        id TEXT PRIMARY KEY,
        type TEXT NOT NULL CHECK (type IN ('store','pick','move')),
        status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','claimed','completed','returned','partial','cancelled')),
        priority TEXT NOT NULL DEFAULT 'normal' CHECK (priority IN ('normal','urgent')),
        assignee_id INTEGER REFERENCES users(id),
        created_by_id INTEGER REFERENCES users(id),
        due_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        completed_at TIMESTAMPTZ,
        note TEXT
      );
      CREATE TABLE IF NOT EXISTS task_items (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        task_id TEXT NOT NULL REFERENCES tasks(id),
        pallet_id TEXT REFERENCES pallets(id),
        sku_id INTEGER NOT NULL REFERENCES skus(id),
        from_location_id INTEGER REFERENCES locations(id),
        to_location_id INTEGER REFERENCES locations(id),
        planned_quantity INTEGER NOT NULL,
        actual_quantity INTEGER,
        returned_quantity INTEGER NOT NULL DEFAULT 0,
        note TEXT,
        outcome TEXT CHECK (outcome IS NULL OR outcome IN ('completed','returned','partial')),
        resolved_at TIMESTAMPTZ
      );
      CREATE TABLE IF NOT EXISTS movements (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        pallet_id TEXT NOT NULL REFERENCES pallets(id),
        sku_id INTEGER NOT NULL REFERENCES skus(id),
        task_id TEXT REFERENCES tasks(id),
        action TEXT NOT NULL CHECK (action IN ('inbound','pick','partial_pick','move','return','adjust')),
        from_location_id INTEGER REFERENCES locations(id),
        to_location_id INTEGER REFERENCES locations(id),
        quantity INTEGER NOT NULL,
        occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        operator_id INTEGER REFERENCES users(id)
      );
      CREATE TABLE IF NOT EXISTS warehouse_revisions (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
      CREATE TABLE IF NOT EXISTS runtime_schema_state (
        id INTEGER PRIMARY KEY,
        version INTEGER NOT NULL,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      );

      CREATE INDEX IF NOT EXISTS sessions_user_idx ON sessions(user_id);
      CREATE INDEX IF NOT EXISTS sessions_expiry_idx ON sessions(expires_at);
      CREATE UNIQUE INDEX IF NOT EXISTS locations_code_type_unique ON locations(code,type);
      CREATE INDEX IF NOT EXISTS locations_type_zone_idx ON locations(type,zone);
      CREATE INDEX IF NOT EXISTS sku_catalog_code_active_idx ON sku_catalog(code,active);
      CREATE INDEX IF NOT EXISTS sku_catalog_client_idx ON sku_catalog(client);
      CREATE INDEX IF NOT EXISTS sku_catalog_import_idx ON sku_catalog(import_key);
      CREATE UNIQUE INDEX IF NOT EXISTS sku_catalog_active_code_unique ON sku_catalog(UPPER(code)) WHERE active=TRUE;
      CREATE INDEX IF NOT EXISTS pallets_sku_idx ON pallets(sku_id);
      CREATE INDEX IF NOT EXISTS pallets_location_idx ON pallets(location_id);
      CREATE INDEX IF NOT EXISTS tasks_status_type_idx ON tasks(status,type);
      CREATE INDEX IF NOT EXISTS task_items_task_idx ON task_items(task_id);
      CREATE INDEX IF NOT EXISTS task_items_resolved_time_idx ON task_items(resolved_at);
      CREATE INDEX IF NOT EXISTS movements_pallet_time_idx ON movements(pallet_id,occurred_at);
      CREATE INDEX IF NOT EXISTS movements_sku_time_idx ON movements(sku_id,occurred_at);
      CREATE INDEX IF NOT EXISTS movements_time_idx ON movements(occurred_at);
      CREATE INDEX IF NOT EXISTS movements_from_time_idx ON movements(from_location_id,occurred_at);
      CREATE INDEX IF NOT EXISTS movements_to_time_idx ON movements(to_location_id,occurred_at);
    `);

    const repaired=await client.query(`
      UPDATE pallets AS pallet
      SET status='in_stock',updated_at=CURRENT_TIMESTAMP
      WHERE pallet.status='in_task'
        AND NOT EXISTS (
          SELECT 1 FROM task_items item
          JOIN tasks task ON task.id=item.task_id
          WHERE item.pallet_id=pallet.id
            AND item.outcome IS NULL
            AND task.status IN ('pending','claimed')
        )
    `);
    if((repaired.rowCount??0)>0) {
      await client.query("INSERT INTO warehouse_revisions (changed_at) VALUES (CURRENT_TIMESTAMP)");
    }
    await client.query(`
      INSERT INTO runtime_schema_state (id,version,updated_at)
      VALUES (1,$1,CURRENT_TIMESTAMP)
      ON CONFLICT(id) DO UPDATE SET version=EXCLUDED.version,updated_at=EXCLUDED.updated_at
    `,[POSTGRES_RUNTIME_SCHEMA_VERSION]);
    await client.query("COMMIT");
  } catch(error) {
    await client.query("ROLLBACK").catch(()=>undefined);
    throw error;
  } finally {
    await client.query("SELECT pg_advisory_unlock(hashtext($1))",[SCHEMA_LOCK]).catch(()=>undefined);
    client.release();
  }
}

export async function isDatabaseReady() {
  await ensureRuntimeSchema();
  await getPool().query("SELECT 1");
}
