import { getPool } from "./index";
import { generateEmployeeId } from "../lib/timekeeping/employee-id";

let initialization:Promise<void>|null=null;
const TIMEKEEPING_SCHEMA_VERSION=4;
const SCHEMA_LOCK="neiku-timekeeping-schema";

export function ensureTimekeepingSchema(){
  initialization??=initialize().catch(error=>{initialization=null;throw error});
  return initialization;
}

async function initialize(){
  const client=await getPool().connect();
  try{
    await client.query("SELECT pg_advisory_lock(hashtext($1))",[SCHEMA_LOCK]);
    await client.query("BEGIN");
    await client.query(`
      CREATE TABLE IF NOT EXISTS time_employees (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        badge_code TEXT NOT NULL UNIQUE,
        employee_code TEXT,
        name TEXT NOT NULL,
        organization_type TEXT NOT NULL DEFAULT 'OZM' CHECK (organization_type IN ('OZM','JJC')),
        active BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
      CREATE TABLE IF NOT EXISTS time_work_items (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        barcode TEXT NOT NULL UNIQUE,
        code TEXT NOT NULL UNIQUE,
        name TEXT NOT NULL,
        client TEXT NOT NULL DEFAULT '内部',
        work_type TEXT NOT NULL CHECK (work_type IN ('wave','standard')),
        wave_no TEXT UNIQUE,
        channel_name TEXT NOT NULL DEFAULT '',
        channel_type TEXT NOT NULL DEFAULT '',
        sku_count INTEGER NOT NULL DEFAULT 0 CHECK (sku_count>=0),
        order_count INTEGER NOT NULL DEFAULT 0 CHECK (order_count>=0),
        piece_count INTEGER NOT NULL DEFAULT 0 CHECK (piece_count>=0),
        sort_order INTEGER NOT NULL DEFAULT 0,
        status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','completed')),
        interrupted_at TIMESTAMPTZ,
        completed_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
      CREATE TABLE IF NOT EXISTS time_shifts (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        employee_id INTEGER NOT NULL REFERENCES time_employees(id),
        work_date TEXT NOT NULL,
        clock_in TIMESTAMPTZ NOT NULL,
        clock_out TIMESTAMPTZ,
        status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','closed')),
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT time_shifts_clock_order CHECK (clock_out IS NULL OR clock_out>clock_in)
      );
      CREATE TABLE IF NOT EXISTS time_attendance_edits (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        request_id TEXT NOT NULL UNIQUE,
        shift_id INTEGER NOT NULL REFERENCES time_shifts(id),
        employee_id INTEGER NOT NULL REFERENCES time_employees(id),
        work_date TEXT NOT NULL,
        attendance_field TEXT NOT NULL CHECK (attendance_field IN ('clock_in','clock_out')),
        old_timestamp TIMESTAMPTZ NOT NULL,
        new_timestamp TIMESTAMPTZ NOT NULL,
        note TEXT NOT NULL,
        editor_user_id INTEGER REFERENCES users(id),
        editor_username TEXT NOT NULL,
        edited_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
      CREATE TABLE IF NOT EXISTS time_work_sessions (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        shift_id INTEGER NOT NULL REFERENCES time_shifts(id),
        employee_id INTEGER NOT NULL REFERENCES time_employees(id),
        work_item_id INTEGER NOT NULL REFERENCES time_work_items(id),
        started_at TIMESTAMPTZ NOT NULL,
        ended_at TIMESTAMPTZ
      );
      CREATE TABLE IF NOT EXISTS time_work_session_edits (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        request_id TEXT NOT NULL UNIQUE,
        session_id INTEGER NOT NULL REFERENCES time_work_sessions(id),
        employee_id INTEGER NOT NULL REFERENCES time_employees(id),
        work_date TEXT NOT NULL,
        session_field TEXT NOT NULL CHECK (session_field IN ('started_at','ended_at')),
        old_timestamp TIMESTAMPTZ NOT NULL,
        new_timestamp TIMESTAMPTZ NOT NULL,
        note TEXT NOT NULL,
        editor_user_id INTEGER REFERENCES users(id),
        editor_username TEXT NOT NULL,
        edited_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
      CREATE TABLE IF NOT EXISTS time_wave_assignments (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        work_item_id INTEGER NOT NULL REFERENCES time_work_items(id) ON DELETE CASCADE,
        employee_id INTEGER NOT NULL REFERENCES time_employees(id),
        role TEXT NOT NULL CHECK (role IN ('lead','helper')),
        assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(work_item_id,employee_id)
      );
      CREATE TABLE IF NOT EXISTS time_scan_events (
        id TEXT PRIMARY KEY,
        terminal_id TEXT NOT NULL,
        operator_user_id INTEGER REFERENCES users(id),
        operator_username TEXT NOT NULL,
        employee_id INTEGER REFERENCES time_employees(id),
        work_item_id INTEGER REFERENCES time_work_items(id),
        scanned_code TEXT NOT NULL,
        event_type TEXT NOT NULL,
        outcome TEXT NOT NULL,
        response_payload JSONB NOT NULL,
        occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
      CREATE TABLE IF NOT EXISTS time_revisions (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
      CREATE TABLE IF NOT EXISTS time_runtime_schema_state (
        id INTEGER PRIMARY KEY,
        version INTEGER NOT NULL,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
      ALTER TABLE time_employees ADD COLUMN IF NOT EXISTS employee_code TEXT;
      ALTER TABLE time_work_items ADD COLUMN IF NOT EXISTS interrupted_at TIMESTAMPTZ;
      CREATE UNIQUE INDEX IF NOT EXISTS time_employees_code_unique ON time_employees(employee_code);
      CREATE UNIQUE INDEX IF NOT EXISTS time_shifts_employee_open_unique ON time_shifts(employee_id) WHERE status='open';
      CREATE INDEX IF NOT EXISTS time_shifts_employee_date_idx ON time_shifts(employee_id,work_date);
      CREATE UNIQUE INDEX IF NOT EXISTS time_work_sessions_employee_active_unique ON time_work_sessions(employee_id) WHERE ended_at IS NULL;
      CREATE INDEX IF NOT EXISTS time_work_sessions_employee_time_idx ON time_work_sessions(employee_id,started_at);
      CREATE INDEX IF NOT EXISTS time_work_sessions_item_time_idx ON time_work_sessions(work_item_id,started_at);
      CREATE INDEX IF NOT EXISTS time_work_session_edits_employee_date_idx ON time_work_session_edits(employee_id,work_date);
      CREATE UNIQUE INDEX IF NOT EXISTS time_wave_assignments_item_lead_unique ON time_wave_assignments(work_item_id) WHERE role='lead';
      CREATE INDEX IF NOT EXISTS time_wave_assignments_employee_idx ON time_wave_assignments(employee_id);
      CREATE INDEX IF NOT EXISTS time_work_items_status_idx ON time_work_items(work_type,status,sort_order);
      CREATE INDEX IF NOT EXISTS time_scan_events_terminal_time_idx ON time_scan_events(terminal_id,occurred_at);
      CREATE INDEX IF NOT EXISTS time_scan_events_employee_time_idx ON time_scan_events(employee_id,occurred_at);
      CREATE INDEX IF NOT EXISTS time_attendance_edits_employee_date_idx ON time_attendance_edits(employee_id,work_date);
    `);
    const employeeRows=(await client.query<{id:number;employee_code:string|null;name:string;organization_type:"OZM"|"JJC"}>("SELECT id,employee_code,name,organization_type FROM time_employees ORDER BY id")).rows;
    const takenEmployeeCodes=new Set(employeeRows.flatMap(row=>row.employee_code?[row.employee_code]:[]));
    for(const employee of employeeRows){
      if(employee.employee_code)continue;
      const employeeCode=await generateEmployeeId(employee.name,employee.organization_type,takenEmployeeCodes);
      await client.query("UPDATE time_employees SET employee_code=$1 WHERE id=$2 AND employee_code IS NULL",[employeeCode,employee.id]);
      takenEmployeeCodes.add(employeeCode);
    }
    const standards=[
      ["JOB-SCAN","SCAN","混件扫描",1],
      ["JOB-SINGLE-SCAN","SINGLE-SCAN","单件扫描",2],
      ["JOB-TODO","TODO","问题单",3],
      ["JOB-WAREHOUSE","WAREHOUSE","仓务",4],
      ["JOB-CLEAN","CLEAN","清洁",5],
    ];
    for(const [barcode,code,name,sortOrder] of standards){
      await client.query(`INSERT INTO time_work_items
        (barcode,code,name,client,work_type,sort_order,status,created_at)
        VALUES ($1,$2,$3,'内部','standard',$4,'active',CURRENT_TIMESTAMP)
        ON CONFLICT(barcode) DO UPDATE SET code=EXCLUDED.code,name=EXCLUDED.name,sort_order=EXCLUDED.sort_order`,
      [barcode,code,name,sortOrder]);
    }
    await client.query(`INSERT INTO time_runtime_schema_state(id,version,updated_at)
      VALUES(1,$1,CURRENT_TIMESTAMP)
      ON CONFLICT(id) DO UPDATE SET version=EXCLUDED.version,updated_at=EXCLUDED.updated_at`,[TIMEKEEPING_SCHEMA_VERSION]);
    await client.query("COMMIT");
  }catch(error){
    await client.query("ROLLBACK").catch(()=>undefined);
    throw error;
  }finally{
    await client.query("SELECT pg_advisory_unlock(hashtext($1))",[SCHEMA_LOCK]).catch(()=>undefined);
    client.release();
  }
}
